ninja: fix TypeError: check_out_dir() missing 1 required positional argument
Bug: 442612621
Change-Id: Ia6dd38e2b8a6b84fcf3abbe9603550af0eb6a8c5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/6914234
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Gavin Mak <gavinmak@google.com>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>